name: Amy Wall
description: "Software Engineer"
meta_description: "Amy Wall, Software Engineer"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "amymariewall.github.io"
# google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Amy Wall"

# Disqus config
disqus-shortname: ""
disable_disk_cache: "true"
